services:
    jgm.url_helper:
        class: JGM\TableBundle\Table\Utils\UrlHelper
        arguments: ["@request_stack","@router"]
    jgm.table_context:
        class: JGM\TableBundle\DependencyInjection\Service\TableContext
    jgm.table_collector:
        class: JGM\TableBundle\DataCollector\TableCollector
        arguments: ["@jgm.table_context","@jgm.table_stopwatch","@jgm.table_hint"]
        public: false
        tags:
            - { name: data_collector, template: 'JGMTableBundle:DataCollector:table_collector', id: 'jgm.table_collector' }
    jgm.table_stopwatch:
        class: JGM\TableBundle\DependencyInjection\Service\TableStopwatchService
        arguments: ["%kernel.debug%"]
    jgm.table_factory:
        class: JGM\TableBundle\DependencyInjection\Service\TableFactoryService
        arguments: ["@service_container","@doctrine.orm.entity_manager","@request_stack","@router","@jgm.table_stopwatch","@jgm.table_hint"]
        tags:
            - { name: jgm.table, channel: jgm }
    jgm.table: '@jgm.table_factory'
    jgm.table_hint:
        class: JGM\TableBundle\DependencyInjection\Service\TableHintService
        arguments: ["%kernel.debug%"]
    jgm.table.twig.attributes_formater:
        class: JGM\TableBundle\Twig\AttributesFormaterExtension
        tags:
            - { name: twig.extension }
    jgm.table.twig.order:
        class: JGM\TableBundle\Twig\OrderExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
    jgm.table.twig.pagination:
        class: JGM\TableBundle\Twig\PaginationExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
    jgm.table.twig:
        class: JGM\TableBundle\Twig\TableExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
    jgm.table.twig.filter:
        class: JGM\TableBundle\Twig\FilterExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
    jgm.table.twig.selection:
        class: JGM\TableBundle\Twig\SelectionExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
    jgm.table.response_listener:
        class: JGM\TableBundle\DependencyInjection\Listener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response }